pipeline {
    agent any

    environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
        SHORT_COMMIT = "${GIT_COMMIT[0..7]}"
	}
    stages {
        stage('Docker Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Build & push Dockerfile') {
            steps {
                sh'
                ansible-playbook playbook.yml --extra-vars tag="$SHORT_COMMIT"'
            }
        }
        stage('Run Dockercompose playbook') {
            steps {
                sh 'ansible-playbook playbook-dcompose.yml'
                
            }
        }
    }
}
